In [1]:
# Data Loading
import pandas as pd
wine_data_path = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv"
wine = pd.read_csv(wine_data_path)
wine.head(1)

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.001,3.0,0.45,8.8,6

In [2]:
import numpy as np

In [3]:
wine.shape

(6497, 13)

In [4]:
wine=wine.dropna()

In [5]:
wine.sample()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2798,white,6.9,0.31,0.32,1.6,0.036,34.0,114.0,0.99068,3.19,0.45,11.4,7

In [6]:
import matplotlib.pyplot as plt

In [7]:
X=wine.iloc[:,1:]
y=wine.iloc[:,0]

In [8]:
X.head(1)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.001,3.0,0.45,8.8,6

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
X_train.shape

(5170, 12)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
knn=KNeighborsClassifier()

In [13]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [14]:
import time
start=time.time()
y_pred=knn.predict(X_test)
print(time.time()-start)

0.08548521995544434

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.945862335653519

In [16]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [17]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [18]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)

In [19]:
X_train_trf=pca.fit_transform(X_train)
X_test_trf=pca.fit_transform(X_test)

In [20]:
X_train_trf.shape

(5170, 3)

In [21]:
X_test_trf.shape

(1293, 3)

In [22]:
knn = KNeighborsClassifier()

In [23]:
knn.fit(X_train_trf,y_train)

KNeighborsClassifier()

In [24]:
y_pred = knn.predict(X_test_trf)

In [25]:
accuracy_score(y_test,y_pred)

0.9783449342614076

In [26]:
for i in range(1,13):
    pca = PCA(n_components=i)
    X_train_trf = pca.fit_transform(X_train)
    X_test_trf = pca.transform(X_test)
    
    knn = KNeighborsClassifier()
    
    knn.fit(X_train_trf,y_train)
    
    y_pred = knn.predict(X_test_trf)
    
    print(accuracy_score(y_test,y_pred))

0.9760247486465584
0.982985305491106
0.982985305491106
0.9876256767208044
0.9868522815158546
0.9891724671307038
0.988399071925754
0.9876256767208044
0.988399071925754
0.9899458623356535
0.9899458623356535
0.9899458623356535

In [27]:
# transforming to a 2D coordinate system
pca = PCA(n_components=2)
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [28]:
X_train_trf

array([[ 2.43383602,  2.11408924],
       [ 0.7161054 , -0.96782145],
       [ 1.87825671,  0.3087484 ],
       ...,
       [-2.77715552,  2.2892406 ],
       [-2.71987143,  1.30399763],
       [-0.63993465,  0.23964726]])

In [29]:
import plotly.express as px
y_train_trf = y_train.astype(str)
fig = px.scatter(x=X_train_trf[:,0],
                 y=X_train_trf[:,1],
                 color=y_train_trf,
                 color_discrete_sequence=px.colors.qualitative.G10
                )
fig.show()

In [30]:
# transforming in 3D
pca = PCA(n_components=3)
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [31]:
X_train_trf

array([[ 2.43383602,  2.11408924, -2.127539  ],
       [ 0.7161054 , -0.96782145,  2.63444927],
       [ 1.87825671,  0.3087484 , -0.56653343],
       ...,
       [-2.77715552,  2.2892406 ,  2.40960642],
       [-2.71987143,  1.30399763,  1.91923015],
       [-0.63993465,  0.23964726,  1.12933172]])

In [33]:
import plotly.express as px
y_train_trf = y_train.astype(str)
fig = px.scatter_3d(wine, x=X_train_trf[:,0], y=X_train_trf[:,1], z=X_train_trf[:,2],
              color=y_train_trf)
fig.update_layout(
    margin=dict(l=20, r=20, t=20, b=20),
    paper_bgcolor="LightSteelBlue",
)
fig.show()

In [34]:
pca.explained_variance_
# Eigen values

array([3.03863301, 2.62435106, 1.63495697])

In [35]:
pca.components_.shape
# Eigen vectors

(3, 12)

In [36]:
pca.explained_variance_ratio_

array([0.25317044, 0.21865362, 0.13622006])