In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.datasets import make_regression
import plotly.graph_objects as go
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [6]:
X,y=make_regression(n_samples=200,n_features=2,n_informative=2,n_targets=1,noise=50)

In [8]:
df=pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})
df

     feature1  feature2      target
0    0.465720  0.540004   62.815773
1   -0.988765  0.497631    0.935356
2   -0.870033 -0.888057 -142.565080
3   -0.699796  0.282435   -2.501998
4    1.222165 -1.046604   73.601106
..        ...       ...         ...
195  0.079156  0.088669 -155.359667
196  0.270641 -0.086028   13.870335
197  1.559435  0.925893  261.204274
198 -0.288050  0.353046  -73.162991
199 -1.976532 -0.669582 -202.753795

[200 rows x 3 columns]

In [9]:

fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.show()

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2,random_state=3)
X_train

     feature1  feature2
156 -0.686003  0.012490
115  1.184467 -0.557263
155  0.449433 -0.318720
15   0.774942  1.749536
61  -0.096713 -0.735323
..        ...       ...
0    0.465720  0.540004
184 -1.055218 -0.801330
131  0.711304  1.304551
152  1.512568  0.761811
106  0.993680 -1.007973

[160 rows x 2 columns]

In [14]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [16]:
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
y_pred

array([  70.84587405,  -57.13154362,  -40.14410444,  230.01311553,
        -71.8048478 ,  130.02190735,   92.00800311, -143.30250137,
       -134.29978454,  181.03525066,   39.87251778,   70.838917  ,
        -87.78258147,   44.7879003 ,  -85.31454791,  238.21362678,
       -144.27349684,  -49.23362615,  305.89697636,  -40.43001219,
         83.50092244,  179.47549147,  -69.28774699,  -48.16315392,
        112.80476786,  -36.17036158,    1.70846634, -191.89827776,
        202.99335311,  123.03124036,   70.43271131,   85.314338  ,
         11.27726064, -180.61666687,  122.68636219,   23.25685941,
         50.22966294,   44.4114146 ,   -1.27299978,   -4.78724245])

In [17]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 37.86865504033777
MSE 2221.4544130001605
R2 score 0.8768949380909319